
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"ryan.z.williams@gmail.com",
    "password":"1"
}

###
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"ryan.z.williams@gmail.com",
    "password":"2"
}

###
POST  http://localhost:3000/user/signup
Content-Type: application/json

{
    "email":"ryan.z.williams@gmail.co",
    "password1":"1"
    
    
}

###
POST  http://localhost:3000/admin/login
Content-Type: application/json

{
    "username":"z_yi23",
    "password":"1"
}

###
POST  http://localhost:3000/admin/login
Content-Type: application/json

{
    "username":"z_yi23",
    "password":"2"
}