
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"ryan.z.williams@gmail.com",
    "password":"1"
}
###
GET http://localhost:3000/user/index
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYmFzaWMiLCJjYW5Xcml0ZSI6dHJ1ZSwiY2FuQnV5Ijp0cnVlLCJfaWQiOiI2MDA0MGRlNWJjM2E4ZmEwNjE2Y2VkNjEiLCJlbWFpbCI6InJ5YW4uei53aWxsaWFtc0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRjNk9XdVIvbHJ1dFhEUlBtTkw1ZHFPV29aTWJadk9KTUpwdVBjcm42SnpTZXhWZHZrNGJsLiIsIl9fdiI6MCwiaWF0IjoxNjExMjUwNTg2fQ.stBmSxE5CBht44Dc1YDaJt6PGzPV9Ix-abntbWdggGM


###
POST  http://localhost:3000/user/signup
Content-Type: application/json

{
    "email":"ryan.z.williams@gmail.com",
    "password":"1"
}

###
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"ryan.z.williams@gmail.com",
    "password":"2"
}
###
POST  http://localhost:3000/admin/login
Content-Type: application/json

{
    "username":"z_yi23",
    "password":"1"
}

###
POST  http://localhost:3000/admin/login
Content-Type: application/json

{
    "username":"z_yi23",
    "password":"2"
}